### ISSUE TITLE
f9 not working for a friend

### ISSUE THREAD

**Issue by ilucky90** [Guad/GTACoop#21]
My friend and me decided to install this mod, everything works fine for me when i press f9  the menu opens, but my friend also installed the mod and the required programs, but once he press f9 ingame nothing happends the menu won't open is there a way to fix this so my friend can play co-op with me?

**Comment by Guad** [comment]
He didn't install it correctly. Have him post his ScriptHookDotNet-[date].log here.

**Comment by ilucky90** [comment]
He checked and that file doens't exist in his gta 5 folder, but the native trainer works fine.

**Comment by rakion99** [comment]
if there no ScriptHookDotNet-[date].log he is missing ScriptHookVDotNet.asi yes .asi and not .dll

**Comment by ilucky90** [comment]
He does actually have the scripthookvdotnet.asi

**Comment by journey-ad** [comment]
He might need .NET framework 4.5 and Visual C++ 2013

**Comment by ilucky90** [comment]
He does have .NET framework 4.5 and visual c++ 2015

**Comment by Guad** [comment]
That's a ScriptHookDotNet issue, check out the thread on gtaforums.com

**Comment by ilucky90** [comment]
Can't seem to find the thread.

**Comment by Guad** [comment]
http://gtaforums.com/topic/789907-community-script-hook-v-net/
or their github,
https://github.com/crosire/scripthookvdotnet

**Comment by xxnamxx** [comment]
hey, ilucky90 did you have any luck with a fix? same issue here with my brother.

**Comment by ilucky90** [comment]
Nope currently didn't find a fix. Which is sad and on gtaforums they don't answer D:

**Comment by xxnamxx** [comment]
Although not the best fix but we ended up using: https://www.gta5-mods.com/tools/gtav-mod-manager

And for some reason it worked.

**Comment by magnosaturno** [comment]
open game as administrator

**Comment by arjunaryas** [comment]
I have a fix for this issue, me too was facing this issue, after every attempt I failed to get it working with F9 key but I finally found a solution, You need to install all the required softwares but make sure to download- ScriptHookVDotNet v2.9.2 version only because in my case none of the other versions are working, even the latest ScriptHookVDotNet  seems to be not working with my game version. I have 3DM cracked version, Only ScriptHookVDotNet v2.9.2 is compatible with my game version for this mod. Now, It's working smoothly.  Try this you won't regret it.
